image: Visual Studio 2019
configuration: Release
version: 3.1.{build}
platform: Any CPU
skip_tags: true

assembly_info:
  patch: true
  file: 'DGJv3\Properties\AssemblyInfo.cs'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)

cache:
  - packages

install:
  - ps: ./CI/appveyor_install.ps1

before_build:
  - nuget restore -Verbosity quiet
  - msbuild /nologo /v:q /t:Clean

build:
  verbosity: minimal

build_script:
  - ps: msbuild /nologo /v:q /p:Configuration="$env:CONFIGURATION" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

for:
-
  branches:
    only:
      - master # including pull requests target at master
  configuration: Release
  before_deploy: # wont run on pull request
    - ps: ./CI/appveyor_deploy.ps1
  deploy: # wont run on pull request
    provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)
    description: "# 点歌姬 $(APPVEYOR_BUILD_VERSION)\n\nCI 自动发布"
    artifact: DGJv3.dll
  artifacts:
    - path: DGJv3\bin\Release
      name: DGJv3.dll

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
